class LogItem:
    name = None
    description = None
    item_id = None
    numeric_id = None
    data_type = None
    deadband_type = None
    deadband_value = None
    deadband_lo_range = None
    deadband_hi_range = None

class OPCTag:
    name = None
    description = None
    tag_address = None
    tag_datatype = None
    read_write_access = None
    scan_rate = None
    autogenerated = None
    scaling_type = None
    scaling_lo_raw = None
    deadband_hi_raw = None
    scaled_data_type = None
    scaled_low = None
    scaled_high = None
    clamp_low = None
    clamp_high = None
    scaling_negate_value = None
    scaling_units = None